SHELL := /bin/bash

help:
	@echo -e "Elixir Style Guide. \n\nAvailable actions:"
	@echo -e "\tmake test\t Test documentation format"
	@echo -e "\tmake compile\t Compile project using mix tool"
	@echo -e "\tmake clean\t Clean all files generated by compile action"

test:
	@echo "Testing project ..."
	rake test

compile:
	@mix deps.get
	@mix docs

clean:
	@echo Cleaning project ...
	@rm -rf "_build/" "doc/" "deps/"
